typography_spectrum: 0.153457
color:
  saturation: 0.588305207900703
  brandStrength: 0.2886070846579969
  rhythmicContrast: 0.2701726513914764
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  lightness: 0.6327629301231354
layout_spectrum: 1
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c524feb9-4520-45f1-91a0-3308d1d368b2.jpg
name: University College Dublin One Health Society
navigation:
  - id: 04934548-b478-44f9-bfc7-7ae61e03e030
    url: 2016-05-20-contact-us.html
    name: Contact Us
    type: content
  - id: 4ab32f9f-44e1-478e-ae1d-dd543361848a
    url: 2016-05-16-about-us.html
    name: About Us
    type: content
  - id: 'https://www.facebook.com/UCDOneHealthSociety/'
    url: 'https://www.facebook.com/UCDOneHealthSociety/'
    name: Facebook
    type: external
  - id: 'https://twitter.com/ucdonehealth'
    url: 'https://twitter.com/ucdonehealth'
    name: Twitter
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/47b57d2f-65cc-4891-b587-659327703bab.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: >-
  Bringing together Human and Veterinary medicine and their interplay with the
  environment for better health outcomes
