typography_spectrum: 0.8015124124940485
color:
  saturation: 0.2729793128091842
  brandStrength: 0.2772862312849611
  rhythmicContrast: 0.7222745399922132
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  lightness: 0.6278557230252773
layout_spectrum: 0.9483614179771394
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c524feb9-4520-45f1-91a0-3308d1d368b2.jpg
name: University College Dublin One Health Society
navigation:
  - name: Contact Us
    id: 04934548-b478-44f9-bfc7-7ae61e03e030
    type: content
  - name: About Us
    id: 4ab32f9f-44e1-478e-ae1d-dd543361848a
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/UCDOneHealthSociety/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/ucdonehealth'
    type: external
  - name: One Health Week 2016
    id: 295167d1-0a8f-45b0-a328-82595d37f6f9
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/47b57d2f-65cc-4891-b587-659327703bab.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: >-
  Bringing together Human and Veterinary medicine and their interplay with the
  environment for better health outcomes
